config/routes.rb
SampleApp::Application.routes.draw do
  resources :standards

  get "videos/favorite"

  resources :users do
	resources :videos
  end
  
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/signup', 	to: 'users#new' 
  match '/signin', 	to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
 
  match '/help',	to: 'static_pages#help'
  match '/about', 	to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class User < ActiveRecord::Base 
  attr_accessible :name, :title, :nickname, :description, :email, :password, :password_confirmation
  has_secure_password
  has_many :videos, dependent: :destroy

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :name,  presence: true, 
					length: { maximum: 50 }
  validates :title,  presence: true, 
					length: { maximum: 50 }					
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
					format: { with: VALID_EMAIL_REGEX }, 
					uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  private
    def create_remember_token
	  self.remember_token = SecureRandom.urlsafe_base64
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user,	only: [:edit, :update]
  before_filter :creating_while_signed_in,	only: [:new, :create]
  before_filter :correct_user, 		only: [:edit, :update]
  before_filter :admin_user, 		only: :destroy

  
  def index 
	@users = User.paginate(page: params[:page])
  end	  
  
  def new
	@user = User.new
  end
  
  def show
	@user = User.find(params[:id]) # or current_user, if not in URL (which may be)
	if signed_in? && current_user?(@user)
		@videos = @user.videos.all	#.paginate(page: params[:page])		
		render 'dashboard'
	else
		@videos = @user.videos.all	#.paginate(page: params[:page])
	end
  end
  
  def edit
  end
  
  def create
	@user = User.new(params[:user])
  	if @user.save
	  sign_in @user
	  flash[:success] = "Welcome to EduTainment!"
	  redirect_to @user
	else
	  render 'new'
	end
  end
  
  def update
	if @user.update_attributes(params[:user])
	  flash[:success] = "Your profile has been updated"
	  sign_in @user			# We sign in as part of successful update because the remember token is reset when the user is saved; this allows a user to change login info and end any floating hijacked sessions
	  redirect_to @user
    else 
	  render 'edit'
	end
  end
  
  def destroy
	if (current_user.admin? && current_user == User.find(params[:id]))
	  redirect_to users_path, notice: "Try again to delete yourself, admin!"
	else
	  User.find(params[:id]).destroy
	  flash[:success] = "User destroyed."
	  redirect_to users_path
	end
  end
  
  private
  
    def signed_in_user
	  unless signed_in?
	    store_location
		redirect_to signin_path, notice: "Please sign in." 
	  end
	end
	
	def creating_while_signed_in
	  if signed_in?
	    redirect_to root_path, notice: "Sign out to create a new user!"
	  end
	end
	
	def correct_user
	  @user = User.find(params[:id])
	  redirect_to(root_path) unless current_user?(@user)
	end
	
	def admin_user
	  redirect_to root_path unless current_user.admin?
	end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user. (Based on user's email)
  def gravatar_for(user, options = { size: 50 } )
	gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	size = options[:size]
	gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
	image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/users/_fields.html.erb
	<%= render 'shared/error_messages' %>

	<%= f.label :name %>
	<%= f.text_field :name %>
	
	<%= f.label :nickname, "aka..." %>
	<%= f.text_field :nickname %>
	
	<%= f.label :title, "What do you call your artist page?" %>
	<%= f.text_field :title %>
	
	<%= f.label :description, "Tell us a little bit about yourself:" %>
	<%= f.text_area :description %>

	<%= f.label :email %>
	<%= f.text_field :email %>	
	
	<%= f.label :password %>
	<%= f.password_field :password %>

	<%= f.label :password_confirmation, "Confirm Password" %>
	<%= f.password_field :password_confirmation %>

app/views/users/_user.html.erb
	<div class="row">
		<div class="span3 content">
			<% if user.videos.any? %>
				<iframe class="content" width="260" height="180" src="<%= user.videos.first.vid_url %>" frameborder="10" allowfullscreen></iframe>
			<% else gravatar_for user, size: 52 %>
			<% end %>
		</div>
		<div class="span3 offset1">
			<br /><br /><br /><br />
			<%= link_to "#{user.title}", user, class: "users" %>
		</div>
		<div class="span3 offset1">
			<p><%= user.description %>
		</div>
	</div>
	<br />

app/views/users/_user_profile.html.erb
	<div class="row">
		<div class="span3 offset1">
			<br /><br /><br /><br />
			<%= link_to "#{user.title}", user, class: "users" %>
		</div>
		<div class="span3 offset1">
			<p><%= user.description %>
		</div>
	</div>
	<br />

app/views/users/dashboard.html.erb
<% provide(:title, "My Dashboard") %>
<div class="container">
	<div class="row">
		<div class="span12 center users">
			<h1><%= @user.title %></h1>
			<div class="row-fluid">
				<div class="span7">
					<h2 class="pull-right">With <%= @user.name %></h2>
				</div>
				<div class="span5 pull-left">
					<%= gravatar_for @user %>
				</div>
			</div>
			<br /><br />
			<div class="row">
				<div class="span8 offset2">
					<p>
						<%= @user.description %>
					</p>
					<br />
				</div>
			</div>
		</div>
	</div>
	
	<br />
	<% if @user.videos.any? %>
		<div class="row">
			<div class="span2">
				<h3>Videos: (<%= @user.videos.count %>)</h3>
			</div>
			<div class="span4 offset6 pull-right">
				<%= render 'shared/searchbar' %>
			</div>
			</br>
		</div>
		<div class="row videos">
			
				<%= render @videos %>
		</div>
	<% end %>

	<div class="row">
		<br />
		<br />
		<div class="span10 center">
			<%= link_to "Add some EDUtainment", new_user_video_path(@user), class: "btn btn-large btn-primary" %>
		</div>
	</div>
</div>
	
<br />
<p>Name: <%= @user.name %></p>
<p>Email: <%= @user.email %></p>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>

			<%= render 'fields', f: f %>
			<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		
		<% end %>
		
		<%= gravatar_for @user %>
		<%= link_to "Change", "http://gravatar.com/emails", target: "_blank" %>
	</div>
</div>

app/views/users/feed.html.erb
<% provide(:title, "Edit Profile") %>
<div class="container">
	<div class="row">
		<div class="span8">
			<%= render @user %>
		</div>
	</div>
	<br />
	<div class="row">
		<div class="span4">
			<%= link_to "Add some EduTainment", new_video_path, class: "btn btn-large btn-primary" %>
		</div>
	</div>
</div>
	
<br />
<p>Name: <%= @user.name %></p>
<p>Email: <%= @user.email %></p>

app/views/users/index.html.erb
<% provide(:title, 'Our Artists') %>
<h1>Our Artists</h1>
 
<%= will_paginate %>
<br />
 <div class="row users">
	<%= render @users %>
</div>
<br />
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
	<%= form_for(@user) do |f| %>
	
	  <%= render 'fields', f: f %>
	  <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
	
	<% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container">
	<div class="row">
		<div class="span12 center users">
			<h1><%= @user.title %></h1>
			<div class="row">
				<div class="span4 offset6">
					<h2 class="pull-right">With <%= @user.name %></h2>
				</div>
				<div class="span2">
					<%= gravatar_for @user %>
				</div>
			</div>
			<br />
			<div class="row">
				<div class="span6 offset3">
					<p>
						<%= @user.description %>
					</p>
					<br /><br />
					<div class="row">
						<div class="span6">
							<% if @user.videos.any? %>
								<iframe width="460" height="315" src="<%= @user.videos.first.vid_url %>" frameborder="10" allowfullscreen></iframe>
							<% end %>
						</div>
					</div>
				</div>
			</div>
			<br />
			<% if @user.videos.any? %>
				<div class="row">
					<div class="span2">
						<h3>Videos: (<%= @user.videos.count %>)</h3>
					</div>
					<div class="span4 offset6 pull-right">
						<%= render 'shared/searchbar' %>
					</div>
				</div>
				<div class="row videos">
					<%= render @videos %>
				</div>
			<% end %>
			<div class="row">
				<p>Name: <%= @user.name %></p>
				<p>Email: <%= @user.email %></p>
			</div>
		</div>
	</div>
</div>
