config/routes.rb
SampleApp::Application.routes.draw do
  resources :standards

  get "videos/favorite"

  resources :users do
	resources :videos
  end
  
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/signup', 	to: 'users#new' 
  match '/signin', 	to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
 
  match '/help',	to: 'static_pages#help'
  match '/about', 	to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  

end

app/models/standard.rb
class Standard < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/standards_controller.rb
class StandardsController < ApplicationController
  # GET /standards
  # GET /standards.json
  def index
    @standards = Standard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @standards }
    end
  end

  # GET /standards/1
  # GET /standards/1.json
  def show
    @standard = Standard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @standard }
    end
  end

  # GET /standards/new
  # GET /standards/new.json
  def new
    @standard = Standard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @standard }
    end
  end

  # GET /standards/1/edit
  def edit
    @standard = Standard.find(params[:id])
  end

  # POST /standards
  # POST /standards.json
  def create
    @standard = Standard.new(params[:standard])

    respond_to do |format|
      if @standard.save
        format.html { redirect_to @standard, notice: 'Standard was successfully created.' }
        format.json { render json: @standard, status: :created, location: @standard }
      else
        format.html { render action: "new" }
        format.json { render json: @standard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /standards/1
  # PUT /standards/1.json
  def update
    @standard = Standard.find(params[:id])

    respond_to do |format|
      if @standard.update_attributes(params[:standard])
        format.html { redirect_to @standard, notice: 'Standard was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @standard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /standards/1
  # DELETE /standards/1.json
  def destroy
    @standard = Standard.find(params[:id])
    @standard.destroy

    respond_to do |format|
      format.html { redirect_to standards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/standards_helper.rb
module StandardsHelper
end

app/views/standards/_form.html.erb
<%= form_for(@standard) do |f| %>
  <% if @standard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@standard.errors.count, "error") %> prohibited this standard from being saved:</h2>

      <ul>
      <% @standard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/standards/edit.html.erb
<h1>Editing standard</h1>

<%= render 'form' %>

<%= link_to 'Show', @standard %> |
<%= link_to 'Back', standards_path %>

app/views/standards/index.html.erb
<h1>Listing standards</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @standards.each do |standard| %>
  <tr>
    <td><%= link_to 'Show', standard %></td>
    <td><%= link_to 'Edit', edit_standard_path(standard) %></td>
    <td><%= link_to 'Destroy', standard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Standard', new_standard_path %>

app/views/standards/new.html.erb
<h1>New standard</h1>

<%= render 'form' %>

<%= link_to 'Back', standards_path %>

app/views/standards/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_standard_path(@standard) %> |
<%= link_to 'Back', standards_path %>